/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LanguageDef, Scenario } from './types';

export const LANGUAGES: LanguageDef[] = [
  {
    code: 'es',
    name: 'Spanish',
    flag: '🇪🇸',
    nativeName: 'Español',
    defaultVoice: 'Kore',
    greeting: '¡Hola! Te doy la bienvenida a la práctica.',
  },
  {
    code: 'fr',
    name: 'French',
    flag: '🇫🇷',
    nativeName: 'Français',
    defaultVoice: 'Zephyr',
    greeting: 'Bonjour ! Bienvenue pour votre entraînement.',
  },
  {
    code: 'de',
    name: 'German',
    flag: '🇩🇪',
    nativeName: 'Deutsch',
    defaultVoice: 'Fenrir',
    greeting: 'Hallo! Willkommen zum Praxistraining.',
  },
  {
    code: 'ja',
    name: 'Japanese',
    flag: '🇯🇵',
    nativeName: '日本語',
    defaultVoice: 'Kore',
    greeting: 'こんにちは！会話の練習を始めましょう。',
  },
  {
    code: 'it',
    name: 'Italian',
    flag: '🇮🇹',
    nativeName: 'Italiano',
    defaultVoice: 'Puck',
    greeting: 'Ciao! Benvenuto alla sessione di pratica.',
  },
  {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    nativeName: 'English',
    defaultVoice: 'Zephyr',
    greeting: 'Hello! Welcome to our conversation practice.',
  },
];

export const SCENARIOS: Scenario[] = [
  {
    id: 'cafe',
    title: 'Warm Café Order',
    description: 'Walk into a charming baker bistro to order a beverage and query the menu.',
    difficulty: 'beginner',
    iconName: 'Coffee',
    characterName: 'Leo',
    characterRole: 'Friendly Barista',
    characterBio: 'Leo is warm, welcoming, and speaks slowly to help learners. He loves craft coffee and takes pride in his pastries.',
    avatarSeed: 'leo',
    suggestedPrompt: 'Order a coffee (espresso or cappuccino) and a chocolate croissant, then ask if they have dairy-free milk alternatives.',
    initialMessage: {
      es: '¡Hola! Bienvenido al Café El Sol. ¿Qué te gustaría tomar hoy?',
      fr: 'Bonjour ! Bienvenue au Café de Paris. Qu’est-ce que je vous sers aujourd’hui ?',
      de: 'Hallo! Willkommen im Café Sonnenschein. Was darf ich dir heute bringen?',
      ja: 'こんにちは！カフェ・ヒカリへようこそ。今日は何にされますか？',
      it: 'Ciao! Benvenuto al Caffè Bella Vita. Cosa vorresti ordinare oggi?',
      en: 'Hello! Welcome to Dawn Bistro. What can I get started for you today?',
    },
  },
  {
    id: 'lost-directions',
    title: 'Navigating the Streets',
    description: 'Ask a friendly local for directions to the metro station or nearest museum.',
    difficulty: 'beginner',
    iconName: 'Map',
    characterName: 'Elena',
    characterRole: 'Local resident',
    characterBio: 'Elena lives nearby. She is polite, creative, and uses highly visual and directional language to explain routes clearly.',
    avatarSeed: 'elena',
    suggestedPrompt: 'Greet Elena, ask where the nearest subway or museum is, and say thank you.',
    initialMessage: {
      es: '¡Hola! Disculpa, ¿puedo ayudarte con algo? Te veo un poco desorientado con el mapa.',
      fr: 'Bonjour ! Pardon, est-ce que vous cherchez votre chemin ? Vous avez l’air un peu perdu.',
      de: 'Hallo! Entschuldigung, kann ich dir helfen? Du siehst aus, als würdest du etwas suchen.',
      ja: 'すみません、道に迷っていますか？何かお探しでしょうか？',
      it: 'Ciao! Scusa, posso aiutarti? Mi sembri un po’ smarrito con quel cellulare.',
      en: 'Excuse me, are you looking for something? You look a bit turned around with that map.',
    },
  },
  {
    id: 'hotel-checkin',
    title: 'Boutique Hotel Check-In',
    description: 'Interact with the reception staff to claim your reservation and get your room key.',
    difficulty: 'intermediate',
    iconName: 'Key',
    characterName: 'Sophia',
    characterRole: 'Front Desk Associate',
    characterBio: 'Sophia is professional, efficient, and eager to accommodate special requests or solve minor booking hiccups.',
    avatarSeed: 'sophia',
    suggestedPrompt: 'Check-in under the name "Morgan", request a quiet room on a higher floor with stable Wi-Fi.',
    initialMessage: {
      es: 'Buenas tardes. Bienvenido a nuestro hotel boutique. ¿Tiene usted una reservación?',
      fr: 'Bonsoir ! Bienvenue à notre hôtel. Avez-vous une réservation sous quel nom ?',
      de: 'Guten Tag! Willkommen im Hotel Central. Haben Sie eine Zimmerreservierung?',
      ja: 'こんにちは！ブティックホテル・さくらへようこそ。ご予約はされておりますでしょうか？',
      it: 'Buonasera! Benvenuto al nostro boutique hotel. Ha una prenotazione a suo nome?',
      en: 'Good afternoon. Welcome to our boutique hotel. Do you have a reservation with us?',
    },
  },
  {
    id: 'job-interview',
    title: 'Modern Tech Interview',
    description: 'Pitch your experience and soft skills in simulated hiring rounds.',
    difficulty: 'advanced',
    iconName: 'Briefcase',
    characterName: 'Marcus',
    characterRole: 'Lead Hiring Manager',
    characterBio: 'Marcus is an experienced tech product manager. He asks challenging but encouraging open-ended questions about teamwork and solving complex bugs.',
    avatarSeed: 'marcus',
    suggestedPrompt: 'Introduce yourself, talk briefly about a programming project you did, and describe how you handle team disagreements.',
    initialMessage: {
      es: 'Hola, un gusto saludarte. Gracias por venir a esta entrevista. Para empezar, ¿podrías hablarme un poco sobre tu experiencia laboral reciente?',
      fr: 'Bonjour, enchanté de vous rencontrer. Merci dʼêtre là. Pour commencer, pourriez-vous mʼexpliquer votre parcours et pourquoi ce rôle vous intéresse ?',
      de: 'Guten Tag, schön Sie kennenzulernen. Vielen Dank für Ihr Kommen. Erzählen Sie mir doch zu Beginn etwas über Ihren beruflichen Werdegang.',
      ja: '本日は面接にお越しいただきありがとうございます。最初に、ご自身のこれまでのご経験と、今回志望された理由について簡単にお聞かせください。',
      it: 'Buongiorno, piacere di conoscerla. Grazie per essere qui. Per iniziare, potrebbe parlarmi brevemente della sua ultima esperienza lavorativa?',
      en: 'Welcome, happy to meet you. Thanks for taking the time to interview today. To start off, could you share a bit about your background and why you are interested in this role?',
    },
  },
  {
    id: 'freeform',
    title: 'Casual Terrace Chat',
    description: 'An open-ended conversation about your personal interests with a supportive penpal.',
    difficulty: 'intermediate',
    iconName: 'MessageSquare',
    characterName: 'Alex',
    characterRole: 'Penpal Buddy',
    characterBio: 'Alex is passionate about traveling, cooking, and hiking. He is a wonderful listener who loves hearing about other cultures.',
    avatarSeed: 'alex',
    suggestedPrompt: 'Chat freely about your day, your language learning goals, some of your hobbies, or what foods you enjoy cooking.',
    initialMessage: {
      es: '¡Qué tal! Qué gusto coincidir contigo. Me estaba tomando un té. Dime, ¿en qué te gusta ocupar tu tiempo libre?',
      fr: 'Salut ! Quel plaisir de discuter avec toi. Je buvais un café en terrasse. Dis-moi, qu’est-ce qui te passionne dans la vie ?',
      de: 'Hi! Schön, dich kennenzulernen. Ich genieße gerade das schöne Wetter. Was machst du eigentlich so am Wochenende?',
      ja: 'やあ！お話しできて嬉しいです。私は今お茶を飲んでいました。普段、休日はどんなことをして過ごすのが好きですか？',
      it: 'Ciao! Che piacere fare due chiacchiere. Mi stavo rilassando un attimo. Raccontami di te: cosa ti piace fare nel tempo libero?',
      en: 'Hey there! So glad to connect with you. I was just unwinding with a drink. Tell me, what do you love doing in your free time?',
    },
  },
];
